In [1]:
import numpy as np
import pandas as pd


N_FOLDS = 5

oof_df = pd.read_parquet('seq_datasets/new_oof_ensemble.parquet')
print(oof_df.shape)

oof_df.head()

(31484534, 42)

,f_0,f_1,f_2,f_3,f_4,f_5,f_6,f_7,f_8,f_9,...,f_32,f_33,id,class,begin,end,kfold,predictionstring,idx,overlap
0,1.0,0.183223,0.185430,0.998034,0.998034,0.998034,0.998034,0.998034,0.998034,0.998034,...,0.790287,0.668874,4AB030046F42,Evidence,83,84,0,83,0,0.011628
1,2.0,0.183223,0.187638,0.998034,0.998154,0.998275,0.998395,0.998515,0.998635,0.998756,...,0.790287,0.668874,4AB030046F42,Evidence,83,85,0,83 84,1,0.023256
2,3.0,0.183223,0.189845,0.998034,0.998275,0.998515,0.998756,0.999031,0.999306,0.999581,...,0.790287,0.668874,4AB030046F42,Evidence,83,86,0,83 84 85,2,0.034884
3,4.0,0.183223,0.192053,0.998034,0.998395,0.998756,0.999169,0.999581,0.999793,1.000004,...,0.790287,0.668874,4AB030046F42,Evidence,83,87,0,83 84 85 86,3,0.046512
4,5.0,0.183223,0.194260,0.998034,0.998515,0.999031,0.999581,0.999697,0.999838,1.000004,...,0.790287,0.668874,4AB030046F42,Evidence,83,88,0,83 84 85 86 87,4,0.058140

In [2]:
gt_df = pd.read_csv("../train_folds.csv")
print(gt_df.shape)
gt_df.head()

(144293, 9)

,id,discourse_id,discourse_start,discourse_end,discourse_text,discourse_type,discourse_type_num,predictionstring,kfold
0,423A1CA112E2,1.622628e+12,8.0,229.0,Modern humans today are always on their phone....,Lead,Lead 1,1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 1...,1
1,423A1CA112E2,1.622628e+12,230.0,312.0,They are some really bad consequences when stu...,Position,Position 1,45 46 47 48 49 50 51 52 53 54 55 56 57 58 59,1
2,423A1CA112E2,1.622628e+12,313.0,401.0,Some certain areas in the United States ban ph...,Evidence,Evidence 1,60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75,1
3,423A1CA112E2,1.622628e+12,402.0,758.0,"When people have phones, they know about certa...",Evidence,Evidence 2,76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 9...,1
4,423A1CA112E2,1.622628e+12,759.0,886.0,Driving is one of the way how to get around. P...,Claim,Claim 1,139 140 141 142 143 144 145 146 147 148 149 15...,1

In [3]:
oof_df = oof_df.drop("kfold", axis=1).merge(gt_df[["id", "kfold"]].drop_duplicates(), on="id", how="left")

oof_df["kfold"].isnull().mean()

0.0

In [ ]:
from utils import score_feedback_comp


score_feedback_comp(oof_df[oof_df["f_7"] > 0.9999], gt_df, return_class_scores=True)

In [ ]:
oof_df["begin"] = oof_df["predictionstring"].apply(lambda x: int(str(x).split()[0]))
#oof_df["end"] = oof_df["predictionstring"].apply(lambda x: int(str(x).split()[-1]))
#oof_df["len"] = oof_df["end"] - oof_df["begin"] + 1
#oof_df["loc"] = (oof_df["begin"] + oof_df["end"]) / 2

oof_df = oof_df.sort_values(["id", "begin"]).reset_index(drop=True)
oof_df.head(20)

In [ ]:
oof_df["target"] = oof_df["overlap"] >= 0.5
oof_df["target"].mean()

In [ ]:
discourse_types = gt_df["discourse_type"].unique()

In [ ]:

#for dtype in discourse_types:
#    oof_df["x"] = oof_df["avg_score"]*(oof_df["class"] == dtype)
#    oof_df[f"sum_{dtype}"] = oof_df.groupby("id")["x"].transform("sum")

#oof_df.drop("x", axis=1, inplace=True)

#oof_df.head()

In [ ]:
from tqdm import tqdm
import os

def read_texts(directory):
    names, texts = [], []
    for f in tqdm(list(os.listdir(directory))):
        names.append(f.replace('.txt', ''))
        texts.append(open(directory + f, 'r').read())
    df = pd.DataFrame({'id': names, 'full_text': texts})
    return df

#text_df = read_texts("data/train/")
#print(text_df.shape)
#text_df.head()

#oof_df = oof_df.merge(text_df, on="id", how="left")

#oof_df["loc_rate"] = oof_df["loc"] / oof_df["full_text"].apply(lambda x: len(x.split()))

In [ ]:
features_dict = {'Lead': [f"f_{i}" for i in range(34)],
 'Position': [f"f_{i}" for i in range(34)],
 'Evidence': [f"f_{i}" for i in range(20)],
 'Claim': [f"f_{i}" for i in range(20)],
 'Concluding Statement': [f"f_{i}" for i in range(34)],
 'Counterclaim': [f"f_{i}" for i in range(17)] + [f"f_{i}" for i in range(27, 34)],
 'Rebuttal': [f"f_{i}" for i in range(17)]}


target = "target"

In [ ]:
import xgboost as xgb
from sklearn.metrics import roc_auc_score, f1_score




param = {'objective': 'reg:logistic',
         'eval_metric': "auc",
         'learning_rate': 0.05,
         'max_depth': 4,
         "min_child_weight": 200,
         "colsample_bynode": 0.8,
         "subsample": 0.5,
         "tree_method": 'gpu_hist', "gpu_id": 1
    }

y_oof = np.zeros(oof_df.shape[0])
res = dict()
best_th = dict()

lvl1_stacking_df = []

for dtype in discourse_types:
    features = features_dict[dtype]

    
    all_indices = np.where(oof_df["class"] == dtype)[0]
    discourse_df = oof_df[oof_df["class"] == dtype].reset_index(drop=True)
    
    tm = discourse_df["target"].mean()
    
    param["scale_pos_weight"] = (1 - tm)/tm
    
    best_its = []
    
    print(dtype, len(features))
    for f in range(N_FOLDS):
        val_ind = all_indices[np.where(discourse_df["kfold"] == f)[0]]
        train_df, val_df = discourse_df[discourse_df["kfold"] != f], discourse_df[discourse_df["kfold"] == f]

        d_train = xgb.DMatrix(train_df[features], train_df[target])
        d_val = xgb.DMatrix(val_df[features], val_df[target])

        model = xgb.train(param, d_train, evals=[(d_val, "val")], num_boost_round=2000, verbose_eval=50, 
                          early_stopping_rounds=50)
        model.save_model(f'gbm_models/xgb_{dtype}_{f}.json')

        y_oof[val_ind] = model.predict(d_val)
        
        best_its.append(model.best_iteration)
        print("...")
        
    discourse_df["prob"] = y_oof[all_indices]
    discourse_df = discourse_df.sort_values(["id", "prob"], ascending=False).reset_index(drop=True)
    
    print("removing overlaps...")
    
    pred_df = []
    prev_id = -1
    overlap_array = np.zeros(4096)
    for id, ps, cls, prob, overlap in zip(discourse_df["id"].values, discourse_df["predictionstring"].values,
                                 discourse_df["class"].values, discourse_df["prob"].values,
                                 discourse_df["overlap"].values):
        if id != prev_id:
            prev_id = id
            overlap_array = np.zeros(4096)
        
        ps_list = ps.split()
        begin, end = int(ps_list[0]), int(ps_list[-1]) + 1
        
        intersect = np.sum(overlap_array[begin:end])
        total = end - begin
        
        condition = intersect <= 1
        
        if dtype in {"Counterclaim", "Rebuttal"}:
            condition = intersect/total <= 0.2
        
        if condition:
            pred_df.append({"id": id, "class": cls, "prob": prob, "predictionstring": ps, "overlap": overlap})
            overlap_array[begin:end] = 1
    
    pred_df = pd.DataFrame(pred_df)
    lvl1_stacking_df.append(pred_df)
    print("tuning...")
    
    thresholds = np.arange(10, 90, 1)/100
    
    all_gt = gt_df[gt_df["discourse_type"] == dtype].shape[0]
    print(pred_df.shape, all_gt)
    f1s = []
    for t in thresholds:
        tp = (pred_df[pred_df["prob"] > t]["overlap"] >= 0.5).sum()
        fp = (pred_df[pred_df["prob"] > t]["overlap"] < 0.5).sum()
        fn = all_gt - tp
        
        f1 = tp / (tp + (fp + fn)/2)
        
        #print(t, tp, fp, fn)
        
        f1s.append(f1)

    best_ind = np.argmax(f1s)
    print()
    print(thresholds[best_ind], f1s[best_ind])
    print()
    
    best_th[dtype] = thresholds[best_ind]
    res[dtype] = f1s
    
    
    #d_train = xgb.DMatrix(discourse_df[features], discourse_df[target])
    #model = xgb.train(param, d_train, num_boost_round=int(np.mean(best_its)*1.2))
    #model.save_model(f'models/xgb_{dtype}.json')

In [ ]:
best_th

In [ ]:
{k: np.mean(v) for k, v in res.items()}

In [ ]:
lvl1_stacking_df = pd.concat(lvl1_stacking_df)
lvl1_stacking_df.shape

In [ ]:
score_feedback_comp(lvl1_stacking_df[lvl1_stacking_df["prob"] > lvl1_stacking_df["class"].map(best_th)], 
                    gt_df, return_class_scores=True)

In [ ]:
xgb.plot_importance(model, importance_type="gain")

In [ ]:
len(oof_df["id"].unique())

In [ ]:
len(gt_df["id"].unique())

In [ ]:
lvl1_stacking_df.to_parquet("cache_oof2/level1_oof.parquet", index=False)

In [ ]:
lvl1_stacking_df.sort_values("prob")

In [ ]:
th_df = pd.DataFrame()

for k, v in res.items():
    th_df[k] = v
    
th_df["threshold"] = np.arange(10, 90, 1)/100

th_df.plot(figsize=(12, 12), x="threshold")