In [6]:
import pickle
import numpy as np

class SeqDataset(object):

    def __init__(self, ids, features, labels, groups, wordRanges, truePos):
        '''
        ids are ids of candidate sequences

        each row of features is 13 features corresponding to the following:
        feature_0: pred_end - pred_start so length of span -1
        feature_1: normalized start position (normalized by number of words)
        feature_2: normalized end position (normalized by number of words)
        feature_4-10: 7 evenly spaced quantiles of the distribution of relevant class probabilities for this sequence
        feature_11: The probability that words on either edge of the current sub-sequence belong to the class of interest
        feature_12: The probability that the first word corresponds to a 'B'-egin token

        labels are binary labels corresponding to whether the candidate sequence is an exact match to a true span

        wordRanges are the start and end (inclusive on both sides) indices of the candidate sequence

        truePos are binary labels corresponding to whether the candidate sequence would be considered a true positive (>0.5 overlap)

        '''
        self.features = np.array(features, dtype=np.float32)
        self.labels = np.array(labels)
        self.groups = np.array(groups, dtype=np.int16)
        self.wordRanges = np.array(wordRanges, dtype=np.int16)
        self.truePos = np.array(truePos)
        self.ids=ids

In [7]:
import pandas as pd

disc_types = ['Evidence','Claim','Lead','Position','Counterclaim','Rebuttal','Concluding Statement']

dfs = []

folder= 'seq_datasets' #put pickle files in this folder
for fold in range(8):
    with open(f'{folder}/valid_seqds_fold{fold}.p','rb') as f:
        seqdataset=pickle.load(f)
        
        for disc_type in disc_types:
            x = seqdataset[disc_type]

            df = pd.DataFrame()
            df[[f"f_{i}" for i in range(x.features.shape[1])]] = x.features
            df["id"] = x.ids
            df["class"] = disc_type
            df[["begin", "end"]] = x.wordRanges
            df["kfold"] = fold
            
            dfs.append(df)
            
            
len_features = x.features.shape[1]

In [8]:
oof_df = pd.concat(dfs)
print(oof_df.shape)
oof_df.head()

(31484534, 39)

,f_0,f_1,f_2,f_3,f_4,f_5,f_6,f_7,f_8,f_9,...,f_29,f_30,f_31,f_32,f_33,id,class,begin,end,kfold
0,1.0,0.183223,0.185430,0.998034,0.998034,0.998034,0.998034,0.998034,0.998034,0.998034,...,-0.183223,-0.119205,0.737307,0.790287,0.668874,4AB030046F42,Evidence,83,84,0
1,2.0,0.183223,0.187638,0.998034,0.998154,0.998275,0.998395,0.998515,0.998635,0.998756,...,-0.183223,-0.119205,0.737307,0.790287,0.668874,4AB030046F42,Evidence,83,85,0
2,3.0,0.183223,0.189845,0.998034,0.998275,0.998515,0.998756,0.999031,0.999306,0.999581,...,-0.183223,-0.119205,0.737307,0.790287,0.668874,4AB030046F42,Evidence,83,86,0
3,4.0,0.183223,0.192053,0.998034,0.998395,0.998756,0.999169,0.999581,0.999793,1.000004,...,-0.183223,-0.119205,0.737307,0.790287,0.668874,4AB030046F42,Evidence,83,87,0
4,5.0,0.183223,0.194260,0.998034,0.998515,0.999031,0.999581,0.999697,0.999838,1.000004,...,-0.183223,-0.119205,0.737307,0.790287,0.668874,4AB030046F42,Evidence,83,88,0

In [9]:
oof_df.sample(3, random_state=0).T

            240218        202850        2338343
f_0            91.0          85.0          27.0
f_1        0.303419      0.679174      0.543651
f_2        0.692308      0.838649      0.650794
f_3        0.000707        0.9968      0.055132
f_4        0.002291      0.999517      0.388843
f_5        0.015181      0.999959      0.973698
f_6        0.021376      0.999987      0.980013
f_7        0.024627      1.000003      0.982496
f_8        0.696721      1.000004      0.982686
f_9        0.907254      1.000067      0.986296
f_10       0.001966      0.004087      0.238046
f_11        0.63453      0.999958      0.056032
f_12       0.000965      0.005216      0.247456
f_13       0.634096      0.999979      0.070107
f_14       0.015443      0.992676      0.741904
f_15       0.000056      0.000166      0.000552
f_16       0.002993      0.000039      0.018074
f_17       0.802198      0.176471      0.777778
f_18       0.461538           0.0      0.925926
f_19       0.009555           0.0        0.0302
f_20        0.21043      0.620404      0.302554
f_21       0.103574      0.163834       0.40095
f_22       0.254955      0.069763      0.001945
f_23       0.062695      0.028571      0.146468
f_24       0.178743      0.017204      0.020601
f_25       0.122123      0.013369      0.018947
f_26       0.059683      0.081115      0.009671
f_27            0.0     -0.232645     -0.281746
f_28            0.0     -0.026266     -0.373016
f_29      -0.303419     -0.679174     -0.527778
f_30       0.636752     -0.628518     -0.527778
f_31       0.179487       0.24015      0.087302
f_32       0.311966      0.273921       0.18254
f_33       0.576923      0.208255      0.396825
id     4BD93FED6367  624A50DFE702  C9B1476CF832
class      Rebuttal      Evidence      Evidence
begin            71           362           137
end             162           447           164
kfold             2             4             2

In [10]:
gt_df = pd.read_csv("../train_folds.csv")
print(gt_df.shape)
gt_df.head()

(144293, 9)

,id,discourse_id,discourse_start,discourse_end,discourse_text,discourse_type,discourse_type_num,predictionstring,kfold
0,423A1CA112E2,1.622628e+12,8.0,229.0,Modern humans today are always on their phone....,Lead,Lead 1,1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 1...,1
1,423A1CA112E2,1.622628e+12,230.0,312.0,They are some really bad consequences when stu...,Position,Position 1,45 46 47 48 49 50 51 52 53 54 55 56 57 58 59,1
2,423A1CA112E2,1.622628e+12,313.0,401.0,Some certain areas in the United States ban ph...,Evidence,Evidence 1,60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75,1
3,423A1CA112E2,1.622628e+12,402.0,758.0,"When people have phones, they know about certa...",Evidence,Evidence 2,76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 9...,1
4,423A1CA112E2,1.622628e+12,759.0,886.0,Driving is one of the way how to get around. P...,Claim,Claim 1,139 140 141 142 143 144 145 146 147 148 149 15...,1

In [ ]:
from tqdm import tqdm


ps = []

for begin, end in tqdm(list(zip(oof_df["begin"].values, oof_df["end"].values))):
    ps.append(" ".join([str(int(x)) for x in range(begin, end)]))

oof_df["predictionstring"] = ps

  8%|â–ˆâ–ˆâ–ˆâ–ˆ                                             | 2578958/31484534 [00:49<02:34, 187014.82it/s]

In [ ]:
oof_df.head()

In [ ]:
from utils import score_feedback_comp


sample_df = oof_df[oof_df["f_7"] > 0.9999].reset_index(drop=True)
print(sample_df.shape)

score_feedback_comp(sample_df, gt_df, return_class_scores=True)

In [ ]:
oof_df["idx"] = np.arange(oof_df.shape[0])

eval_df = oof_df[["idx", "id", "class", "predictionstring"]].merge(gt_df[["id", "discourse_type", "predictionstring"]].rename(columns={"predictionstring": "gt_ps",
                                                                                          "discourse_type": 'class'}), 
                      how="left", on=["id", "class"])
eval_df.shape

In [ ]:
def calc_overlap(predictionstring, gt_ps):

    set_pred = set(str(predictionstring).split(" "))
    set_gt = set(str(gt_ps).split(" "))
    # Length of each and intersection
    len_gt = len(set_gt)
    len_pred = len(set_pred)
    inter = len(set_gt.intersection(set_pred))
    overlap_1 = inter / len_gt
    overlap_2 = inter / len_pred
    return min(overlap_1, overlap_2)



overlap = []

for predictionstring, gt_ps in tqdm(list(zip(eval_df["predictionstring"].values, eval_df["gt_ps"].values))):
    overlap.append(calc_overlap(predictionstring, gt_ps))
    
    
eval_df["overlap"] = overlap

In [ ]:
eval_df = eval_df.groupby("idx")["overlap"].max().reset_index()
eval_df.shape

In [ ]:
eval_df.head()

In [ ]:
eval_df.tail()

In [ ]:
oof_df.head()["idx"], oof_df.tail()["idx"]

In [ ]:
oof_df["overlap"] = eval_df["overlap"].values

oof_df["overlap"].fillna(0.0, inplace=True)

oof_df["overlap"].hist(bins=50)

In [ ]:
oof_df.to_parquet(f"{folder}/new_oof_ensemble.parquet", index=False)